### PR TITLE
Fixed display of safe readonly fields in TabularInline, StackedInline

### PR DESCRIPTION
**Pull request by schampilomatis**
I made a small fix to display readonly strings that are marked safe as is in TabularInline and StackedInline.

### CODE REVIEW

**Comment by kmmbvnr** [comment]
Mm.. thanks for the fix

How can I reproduce the issue?

**Comment by schampilomatis** [comment]
Hi Mikhail,
I faced this issue moving from a normal admin page, where I was using
custom functions in TabularInline to show custom html elements (in my case
links to other parts of the admin page). An example is this:

from django.utils.html import mark_safe
from django.contrib import admin
from .models import Test

# I assume that there is a Test model

class TestInline(admin.TabularInline):

    model = Test

    def html_field(self, instance):
        if instance.id:
            return mark_safe(u'<a href="www.google.com">Edit</a>')

        return ""

    readonly_fields = ('html_field',)



class TestAdmin(admin.ModelAdmin):
    inlines = [
        TestInline,
    ]

admin.site.register(Test, TestAdmin)

**Comment by kmmbvnr** [comment]
mm `{%if field.contents|escape == field.contents %}` a bit hacky solution. We need to find a better one

**Comment by kmmbvnr** [comment]
Yeah, ufortunatelly after a while i didn't see the way to fix this in another way.

`field.contents()` is always a safe string and there is no way to get an idea how it should be rendered properly

**Comment by kmmbvnr** [comment]
But the proposed in the PR solution is broken the same way (

**Pull request merged**
