### PR TITLE
Arabic support

### PR DESCRIPTION
**Pull request by myaser**
adding Arabic .po file and rtl css files

### CODE REVIEW

**Comment by kmmbvnr** [comment]
Thank you for the contribution!

The MaterializeCSS library have no RTL support (https://github.com/Dogfalo/materialize/pull/4391)

Django Material build MaterializeCSS library from the source https://github.com/viewflow/django-material/blob/master/gulpfile.babel.js#L45

If `rtlcss` really works, I think it's really good news for everyone.

Could be have `rltcss` build integrated into django-material gulp file?

**Comment by A-Allam** [comment]
@kmmbvnr what do you mean by 

> Could be have `rltcss` build integrated into django-material gulp file?

**Comment by kmmbvnr** [comment]
I supposed you made rtl CSS files automatically with rtlcss tool. Is it right?

At this case the rtlcss call could be included into the build in Django-material gulp file.

**Comment by kmmbvnr** [comment]
So, I tried the automatic conversion, and it doesn't work by default very well.

screenshot from 2017-06-01 08-56-18

I think the right solution would add RTL support to the MaterializeCSS itself, with proper rltcss config and [value directives](http://rtlcss.com/learn/usage-guide/value-directives/)

Please discuss this at https://github.com/Dogfalo/materialize/pull/4391

**Comment by j209** [comment]
[](https://github.com/atechni/materialize-rtl-support)
[](https://github.com/MahdiMajidzadeh/materialize-rtl)

**Comment by j209** [comment]
[link1](https://github.com/MahdiMajidzadeh/materialize-rtl)
[link2](https://github.com/atechni/materialize-rtl-support)

**Pull request closed without merging**
