### PR TITLE
update materialize to 0.100.1

### PR DESCRIPTION
**Pull request by 7wonders**

### CODE REVIEW

**Comment by kmmbvnr** [comment]
That's wrong way to update the dependencies.

**Comment by kmmbvnr** [comment]
I'll work on this, but a bit later

**Comment by 7wonders** [comment]
Sorry, my bad. Wasn't paying much enough attention and didn't see that they were included in the gulp scripts. Just tried now but gulp is throwing an error 
```
GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected token: name (_defaults)
File: django-material/material/static/material/js/materialize.admin.min.js
Line: 21399
```

**Comment by kmmbvnr** [comment]
Thank you for your help, but it's not required. I'll work on this later.

**Pull request closed without merging**
